# Generated by Django 4.1.3 on 2023-01-12 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('name', models.CharField(max_length=256, verbose_name="Nom de l'équipe")),
                ('permission', models.CharField(blank=True, max_length=256, verbose_name='permision')),
            ],
            options={
                'verbose_name': 'Equipe',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Mise à jour le')),
                ('name', models.CharField(max_length=256, verbose_name='Nom du workspace')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('state', models.CharField(max_length=20, verbose_name='Etat')),
                ('kind', models.CharField(max_length=20, verbose_name='Type')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Espace de travail',
                'verbose_name_plural': 'Espaces de travail',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined_team', models.DateTimeField(auto_now_add=True, verbose_name='Intégré(e) le')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Etat')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.team', verbose_name='Equipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Equipe-utilisateur',
                'verbose_name_plural': 'Equipes-Utilisateurs',
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='workspace.UserTeam', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workspace.workspace', verbose_name='Workspace'),
        ),
    ]
